export const groupedCities = [
  {
    label: "DKI Jakarta",
    items: [
      { label: "Jakarta Pusat", value: "Jakarta Pusat" },
      { label: "Jakarta Barat", value: "Jakarta Barat" },
      { label: "Jakarta Selatan", value: "Jakarta Selatan" },
      { label: "Jakarta Timur", value: "Jakarta Timur" },
      { label: "Jakarta Utara", value: "Jakarta Utara" },
    ],
  },
  {
    label: "Jawa Barat",
    items: [
      { label: "Bandung", value: "Bandung" },
      { label: "Bandung Barat", value: "Bandung Barat" },
      { label: "Bekasi", value: "Bekasi" },
      { label: "Bogor", value: "Bogor" },
      { label: "Ciamis", value: "Ciamis" },
      { label: "Cianjur", value: "Cianjur" },
      { label: "Cirebon", value: "Cirebon" },
      { label: "Depok", value: "Depok" },
      { label: "Garut", value: "Garut" },
      { label: "Indramayu", value: "Indramayu" },
      { label: "Karawang", value: "Karawang" },
      { label: "Kuningan", value: "Kuningan" },
      { label: "Majalengka", value: "Majalengka" },
      { label: "Purwakarta", value: "Purwakarta" },
      { label: "Subang", value: "Subang" },
      { label: "Sukabumi", value: "Sukabumi" },
      { label: "Sumedang", value: "Sumedang" },
      { label: "Tasikmalaya", value: "Tasikmalaya" },
    ],
  },
  {
    label: "Jawa Tengah",
    items: [
      { label: "Semarang", value: "Semarang" },
      { label: "Solo", value: "Solo" },
      { label: "Magelang", value: "Magelang" },
      { label: "Salatiga", value: "Salatiga" },
      { label: "Pekalongan", value: "Pekalongan" },
      { label: "Tegal", value: "Tegal" },
      { label: "Brebes", value: "Brebes" },
      { label: "Cilacap", value: "Cilacap" },
      { label: "Purwokerto", value: "Purwokerto" },
      { label: "Kudus", value: "Kudus" },
      { label: "Jepara", value: "Jepara" },
      { label: "Pati", value: "Pati" },
    ],
  },
  {
    label: "DI Yogyakarta",
    items: [
      { label: "Yogyakarta", value: "Yogyakarta" },
      { label: "Sleman", value: "Sleman" },
      { label: "Bantul", value: "Bantul" },
      { label: "Kulon Progo", value: "Kulon Progo" },
      { label: "Gunungkidul", value: "Gunungkidul" },
    ],
  },
  {
    label: "Jawa Timur",
    items: [
      { label: "Surabaya", value: "Surabaya" },
      { label: "Malang", value: "Malang" },
      { label: "Sidoarjo", value: "Sidoarjo" },
      { label: "Gresik", value: "Gresik" },
      { label: "Mojokerto", value: "Mojokerto" },
      { label: "Jember", value: "Jember" },
      { label: "Banyuwangi", value: "Banyuwangi" },
      { label: "Kediri", value: "Kediri" },
      { label: "Blitar", value: "Blitar" },
      { label: "Pasuruan", value: "Pasuruan" },
      { label: "Probolinggo", value: "Probolinggo" },
    ],
  },
  {
    label: "Banten",
    items: [
      { label: "Tangerang", value: "Tangerang" },
      { label: "Tangerang Selatan", value: "Tangerang Selatan" },
      { label: "Serang", value: "Serang" },
      { label: "Cilegon", value: "Cilegon" },
      { label: "Lebak", value: "Lebak" },
      { label: "Pandeglang", value: "Pandeglang" },
    ],
  },
  {
    label: "Bali",
    items: [
      { label: "Denpasar", value: "Denpasar" },
      { label: "Badung", value: "Badung" },
      { label: "Gianyar", value: "Gianyar" },
      { label: "Tabanan", value: "Tabanan" },
      { label: "Buleleng", value: "Buleleng" },
      { label: "Karangasem", value: "Karangasem" },
    ],
  },
  {
    label: "Sumatera Utara",
    items: [
      { label: "Medan", value: "Medan" },
      { label: "Binjai", value: "Binjai" },
      { label: "Deli Serdang", value: "Deli Serdang" },
      { label: "Pematangsiantar", value: "Pematangsiantar" },
      { label: "Tebing Tinggi", value: "Tebing Tinggi" },
    ],
  },
  {
    label: "Sumatera Selatan",
    items: [
      { label: "Palembang", value: "Palembang" },
      { label: "Prabumulih", value: "Prabumulih" },
      { label: "Lubuk Linggau", value: "Lubuk Linggau" },
      { label: "Muara Enim", value: "Muara Enim" },
    ],
  },
  {
    label: "Sulawesi Selatan",
    items: [
      { label: "Makassar", value: "Makassar" },
      { label: "Gowa", value: "Gowa" },
      { label: "Maros", value: "Maros" },
      { label: "Parepare", value: "Parepare" },
      { label: "Palopo", value: "Palopo" },
    ],
  },
];
